### PR TITLE
Update shared.css for "Smaller Quick Access Tabs"

### PR DESCRIPTION
**Pull request by ManedCalico**
Hello,

I just did a Pull Request on theme.json, which requires this update to work properly.

This changes height from static pixel value to the slider variable set by the user.

Thanks!

### CODE REVIEW

**Comment by rasitayaz** [comment]
will check it when I get the chance, thank you

**Comment by ManedCalico** [comment]
No problem, please let me know if you have any feedback for me. Thanks!

**Review by rasitayaz — APPROVED** [review]
you needn't open a different pull request for each file :)

**Comment by ManedCalico** [comment]
Oh oops, sorry about that! Thanks for letting me know!

**Pull request merged**
